export enum Queues {
    ADMIN_SIGNUP_QUEUE = "ADMIN_SIGNUP_QUEUE",
    DOCTOR_SIGNUP_QUEUE = "DOCTOR_SIGNUP_QUEUE",
    CLIENT_STATUS_QUEUE = "CLIENT_STATUS_QUEUE",
    DOCTOR_STATUS_QUEUE = "DOCTOR_STATUS_QUEUE",
    CLIENT_DOCTOR_PROFILE_QUEUE = "CLIENT_DOCTOR_PROFILE_QUEUE",
    ADMIN_DOCTOR_PROFILE_QUEUE = "ADMIN_DOCTOR_PROFILE_QUEUE",
    CLIENT_DOCTOR_APPROVAL_QUEUE = 'CLIENT_DOCTOR_APPROVAL_QUEUE',
    DOCTOR_DOCTOR_APPROVAL_QUEUE = 'DOCTOR_DOCTOR_APPROVAL_QUEUE'
}
