export enum Queues {
    ADMIN_SIGNUP_QUEUE = "ADMIN_SIGNUP_QUEUE",
    DOCTOR_SIGNUP_QUEUE = "DOCTOR_SIGNUP_QUEUE",
    CLIENT_STATUS_QUEUE = "USER_STATUS_QUEUE",
    DOCTOR_STATUS_QUEUE = "DOCTOR_STATUS_QUEUE",
}
